# Generated by Django 5.0.6 on 2024-07-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polera',
            fields=[
                ('id_polera', models.AutoField(db_column='IdPolera', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('detalle', models.TextField()),
                ('precio', models.IntegerField()),
                ('envio', models.TextField()),
                ('rutaImg1', models.CharField(max_length=100)),
                ('rutaImg2', models.CharField(max_length=100)),
                ('rutaImg3', models.CharField(max_length=100)),
            ],
        ),
    ]
