# Generated by Django 5.0.6 on 2024-07-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poleron',
            fields=[
                ('id_poleron', models.AutoField(db_column='IdPoleron', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('detalle', models.TextField()),
                ('precio', models.IntegerField()),
                ('envio', models.TextField()),
                ('rutaImg1', models.CharField(max_length=100)),
                ('rutaImg2', models.CharField(max_length=100)),
                ('rutaImg3', models.CharField(max_length=100)),
            ],
        ),
    ]
