# Generated by Django 5.0.6 on 2024-07-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owen', '0003_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=75),
        ),
    ]
