# Generated by Django 5.0.6 on 2024-07-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owen', '0004_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=20),
        ),
    ]
