# Generated by Django 5.0.6 on 2024-07-15 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owen', '0005_alter_usuario_apellido_alter_usuario_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='region',
        ),
    ]
